# Generated by Django 4.2.26 on 2025-12-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_roles',
            field=models.CharField(choices=[('Worker', 'Worker'), ('Employer', 'Employer')], default='Employer', max_length=255),
        ),
    ]
