# Generated by Django 4.2.26 on 2025-11-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_categorymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementmodel',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
