# Generated by Django 4.2.26 on 2025-11-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_advertisementmodel_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementmodel',
            name='job_time',
            field=models.CharField(default='9:00 dan 18:00', max_length=255),
        ),
    ]
