# Generated by Django 4.2.26 on 2025-11-30 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_employerprofile_job_applymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='advertisement.categorymodel'),
            preserve_default=False,
        ),
    ]
