# Generated by Django 4.2.26 on 2025-11-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
