# Generated by Django 4.2.26 on 2025-11-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='phone_number',
            field=models.CharField(default='998992606296', max_length=14),
        ),
    ]
