# Generated by Django 4.2.26 on 2025-11-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_alter_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='Tasnif'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=155, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='job',
            name='phone_number',
            field=models.CharField(default='998992606296', max_length=14, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Maosh'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlovha'),
        ),
    ]
