# Generated by Django 4.2.26 on 2025-12-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0011_application_delete_applymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='To‘liq ism')),
                ('profession', models.CharField(max_length=255, verbose_name='Kasbi')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('location', models.CharField(max_length=155, verbose_name='Manzil')),
                ('phone_number', models.CharField(max_length=14, verbose_name='Telefon raqam')),
            ],
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
    ]
