# Generated by Django 4.2.26 on 2025-12-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0012_worker_alter_job_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Holati'),
        ),
    ]
