# Generated by Django 4.2.26 on 2025-12-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0014_alter_worker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Maosh'),
        ),
    ]
