# Generated by Django 4.2.26 on 2025-12-23 15:30

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0015_worker_salary'),
    ]

    operations = [
    migrations.AddField(
        model_name='worker',
        name='created_at',
        field=models.DateTimeField(
            auto_now_add=True,
            default=django.utils.timezone.now
        ),
        preserve_default=False,
    ),
]