# Generated by Django 4.2.26 on 2025-12-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0016_worker_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Kategorya nomi'),
        ),
    ]
